version: '2'
services:
  database:
    build: ./db
    environment:
     - MYSQL_ROOT_PASSWORD=rem
  controller_init:
    build: ./init_device_locations
    environment:
     - MYSQL_ENV=database
    depends_on:
     - "database"
    command: ["./wait-for-it.sh", "-t", "0", "database:3306", "--", "python3","init_devices.py"]
  controller_rem:
    build: ./rem_console
    environment:
     - MYSQL_ENV=database
    depends_on:
     - "database"
    stdin_open: true
    tty: true
    command: ["./wait-for-it.sh", "-t", "0", "database:3306", "--", "python3","REM_console.py"]
  controller_nodes:
    build: ./node_controller
    environment:
     - MYSQL_ENV=database
    depends_on:
     - "database"
    stdin_open: true
    tty: true
    command: ["./wait-for-it.sh", "-t", "0", "database:3306", "--", "uniflex-agent", "--config", "/app/config_master.yaml"]
    network_mode: "host"
  controller_rrm:
    build: ./rrm_controller
    environment:
     - MYSQL_ENV=database
    depends_on:
     - "database"
    command: ["./wait-for-it.sh", "-t", "0", "database:3306", "--", "uniflex-agent", "--config", "/app/config_rrm.yaml"]
    network_mode: "host"
  broker:
    image: uniflex/broker
    ports:
     - "8989:8989"
     - "8990:8990"
    expose:
     - "8989"
     - "8990"
    network_mode: "host"
